#-------------------------------
# General Site Settings
title: Lva2
logo: logo.svg # You can add own logo.
description: Revista de matemáticas Lva<sup>2</sup>


#-------------------------------
# Author Settings
author:
  name: Retos Matemáticos
  image: inicio.png
  say-hello: ¡Hola!, bienvenidos a <strong>Lva<sup>2</sup></strong>
  bio: Revista de divulgación matemática, nacida en el seno del grupo de Telegram <a href="https://t.me/Retos_Matematicos" target="_blank">Retos Matemáticos</a>.


#-------------------------------
# Contact links
#twitter: https://twitter.com/ # Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle


#-------------------------------
# Instagram Feed
#instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
#instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
